name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    -name: dep
      run: sudo apt install build-essential make nasm bison flex
    - name: make
      run: make
